$base: http://borg.kaust.edu.sa/hg-schema
$namespaces:
  sch: https://schema.org/
  efo: http://www.ebi.ac.uk/efo/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  edam: http://edamontology.org/
  evs: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#

$graph:

- name: MainSchema
  type: record
  documentRoot: true
  fields:
    id:
      doc: The subject (eg the fasta/fastq file) that the metadata describes
      type: string
      jsonldPredicate:
        _id: "@id"
        _type: "@id"
        noLinkCheck: true
    sex:
      doc: Sex of the host as defined in PATO, expect Male (http://purl.obolibrary.org/obo/PATO_0000384) or Female (http://purl.obolibrary.org/obo/PATO_0000383) or in Intersex (http://purl.obolibrary.org/obo/PATO_0001340)
      type: string?
      jsonldPredicate:
        _id: http://purl.obolibrary.org/obo/PATO_0000047
        _type: "@id"
        noLinkCheck: true
